# Generated by Django 4.2.7 on 2025-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_offers', models.IntegerField(default=0)),
                ('total_junkyards', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إحصائيات الداشبورد',
                'verbose_name_plural': 'إحصائيات الداشبورد',
                'ordering': ['-date'],
            },
        ),
    ]
