# Generated by Django 4.2.7 on 2025-09-05 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunkyardStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('junkyard_manager', 'مدير التشليح'), ('junkyard_staff', 'موظف التشليح')], default='junkyard_staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('junkyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='bot.junkyard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junkyard_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'junkyard')},
            },
        ),
    ]
