# Generated by Django 4.2.7 on 2025-09-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_junkyardstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='parts',
            field=models.TextField(blank=True, help_text='Required parts description (legacy field)'),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the part/item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional description of the item')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity needed')),
                ('media_files', models.JSONField(blank=True, default=list, help_text='Telegram file IDs for photos/videos of this specific item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.request')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
