# Generated by Django 4.2.7 on 2025-09-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_request_parts_requestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='Expected delivery time', max_length=100),
        ),
    ]
