# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_offer_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit price per item', max_digits=12, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='currency',
            field=models.CharField(blank=True, default='SAR', help_text='Currency code', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description of the item (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity needed (DEPRECATED - fixed to 1)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='Expected delivery time (DEPRECATED)', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Total offer price', max_digits=10),
        ),
    ]
