# Generated by Django 4.2.7 on 2025-09-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_add_unit_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this specific item', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.offer')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='bot.requestitem')),
            ],
            options={
                'unique_together': {('offer', 'request_item')},
            },
        ),
    ]
